# -*- coding: utf-8 -*-
"""workforce_displacement.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10b6rUiTv0hZSDtD1mK4Qa-vGjoIggKRU
"""

import pandas as pd
import streamlit as st

# Load the cleaned dataset for better performance and accuracy
# Ensure this matches the permanent Drive path we established earlier
df = pd.read_csv("cleaned_workforce_data.csv")

st.title("🌐 AI Workforce Risk Calculator")
st.markdown("---")

# User Inputs derived from the global dataset
sector = st.selectbox("Select your Industry:", sorted(df['industry_sector'].unique()))
income = st.selectbox("Select Country Income Group:", sorted(df['income_group'].unique()))

# Filter logic for future 2026 projections
filtered_data = df[(df['industry_sector'] == sector) &
                    (df['income_group'] == income) &
                    (df['year'] == 2026)]

if not filtered_data.empty:
    # Calculating key metrics to demonstrate data-driven insights
    avg_risk = filtered_data['sector_automation_risk_score'].mean()
    wage_premium = filtered_data['ai_skill_wage_premium_pct'].mean()
    displaced = filtered_data['pct_sector_workforce_displaced'].mean()

    # Dashboard Layout
    col1, col2, col3 = st.columns(3)
    col1.metric("Automation Risk", f"{avg_risk:.2f}")
    col2.metric("Displacement %", f"{displaced*100:.1f}%")
    col3.metric("Wage Premium", f"+{wage_premium*100:.1f}%")

    st.success(f"**Insight:** For the **{sector}** sector in **{income}** regions, upskilling provides a **{wage_premium*100:.1f}% wage premium**.")
else:
    st.warning("No data found for this specific selection. Please try a different combination.")